org: lucasmarcelli
app: stonks
service: stonks

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt
    - yarn.lock

custom:
  dynamodb:
    stages: 
      - dev
        prod
    start:
      migrate: true
    
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.8
  region: ca-central-1
  stage: ${opt:stage, 'dev'}
  environment: 
    STAGE: ${self:provider.stage}
  apiKeys:
    - key
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"


functions:
  # handle-event-stream:
    # handler: stonks/eventstream.handler
    # reservedConcurrency: 10
    # events:
    #   - stream: arn:aws:dynamodb:ca-central-1:914050192047:table/dev-stonks-event/stream/2020-04-28T18:11:12.326
  
  # handle-event-stream:
  #   handler: stonks/eventstream.handler
  #   reservedConcurrency: 10
  #   events:
  #     - stream: arn:aws:dynamodb:ca-central-1:914050192047:table/prod-stonks-event/stream/2020-04-29T17:07:29.603

  get-event:
    handler: stonks/queries/event.get
    events:
      - http:
          path: stonks/events/{eventId}
          method: get
          integration: lambda
          cors: true
          private: true
          request:
            parameters:
              paths:
                eventId: true

  create-bank-transaction:
    handler: stonks/commands/bank.create
    events:
      - http:
          path: stonks/banktransaction
          method: post
          cors: true
          private: true

  create-trade:
    handler: stonks/commands/trades.create
    events:
      - http:
          path: stonks/trades
          method: post
          cors: true
          private: true

  list-trades:
    handler: stonks/queries/trades.list
    events:
      - http:
          path: stonks/trades
          method: get
          cors: true
          private: true
          integration: lambda

  get-trade:
    handler: stonks/queries/trades.get
    events:
      - http:
          path: stonks/trades/{eventId}
          method: get
          integration: lambda
          cors: true
          private: true
          request:
            parameters:
              paths:
                eventId: true

  get-holding:
    handler: stonks/queries/holdings.get
    events:
      - http:
          path: stonks/holdings/{consumerId}
          method: get
          integration: lambda
          cors: true
          private: true
          request:
            parameters:
              paths:
                consumerId: true
  
  get-all-accounts:
    handler: stonks/queries/accounts.getAll
    events:
      - http:
          path: stonks/accounts
          method: get
          cors: true
          private: true
          integration: lambda

  get-holding-by-symbol:
    handler: stonks/queries/holdings.getBySymbol
    events:
      - http:
          path: stonks/holdings
          method: get
          integration: lambda
          cors: true
          private: true
          request:
            parameters:
              querystrings:
                symbol: true
    
  list-holdings:
    handler: stonks/queries/holdings.list
    events:
      - http:
          path: stonks/holdings
          method: get
          cors: true
          private: true
          integration: lambda
          
resources:
  Resources:
    StonkEventsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: eventDateTime
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: eventDateTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
        TableName: ${self:provider.stage}-stonks-event
    StonkHoldingTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: holdingId
            AttributeType: S
          - AttributeName: updatedAt
            AttributeType: S
          - AttributeName: symbol
            AttributeType: S
        KeySchema:
          - AttributeName: holdingId
            KeyType: HASH
          - AttributeName: updatedAt
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: SymbolIndex
            KeySchema:
            - AttributeName: symbol
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '5'
              WriteCapacityUnits: '5'
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
        TableName: ${self:provider.stage}-stonks-holding
    StonkAccountsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: accountId
            AttributeType: S
          - AttributeName: updatedAt
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
          - AttributeName: updatedAt
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: NameIndex
            KeySchema:
            - AttributeName: name
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '5'
              WriteCapacityUnits: '5'
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
        TableName: ${self:provider.stage}-stonks-accounts
    


